dist: xenial

language: python

python: "3.7"

install:
  - make update

jobs:
  include:
    # First stage
    - stage: "Basic Tests"
      name: "Typecheck"
      script: make mypy
    - name: "Lint"
      script: make lint
    - name: "Check import"
      script: make verify_import
    # Second stage
    - stage: "Deployment"
      install: skip
      script: skip
      deploy:
        provider: pypi
        on:
          tags: true
          branch:
            - master
            - /v?(\d+\.)?(\d+\.)?(\*|\d+)$/
        # Your pypi username
        user: smoehrle
        password : ${PYPI_PASSWORD}
