# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    List as typing___List,
    Optional as typing___Optional,
    Text as typing___Text,
    Tuple as typing___Tuple,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
builtin___str = str


class MetaDataV1(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Environment(builtin___int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: builtin___int) -> builtin___str: ...
        @classmethod
        def Value(cls, name: builtin___str) -> 'MetaDataV1.Environment': ...
        @classmethod
        def keys(cls) -> typing___List[builtin___str]: ...
        @classmethod
        def values(cls) -> typing___List['MetaDataV1.Environment']: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[builtin___str, 'MetaDataV1.Environment']]: ...
        UNKNOWN_ENVIRONMENT = typing___cast('MetaDataV1.Environment', 0)
        PRODUCTION = typing___cast('MetaDataV1.Environment', 1)
        DEVELOPMENT = typing___cast('MetaDataV1.Environment', 2)
    UNKNOWN_ENVIRONMENT = typing___cast('MetaDataV1.Environment', 0)
    PRODUCTION = typing___cast('MetaDataV1.Environment', 1)
    DEVELOPMENT = typing___cast('MetaDataV1.Environment', 2)

    iso_date = ... # type: typing___Text
    environment = ... # type: MetaDataV1.Environment
    sending_service = ... # type: typing___Text
    offset = ... # type: builtin___int
    partition = ... # type: builtin___int

    def __init__(self,
        *,
        iso_date : typing___Optional[typing___Text] = None,
        environment : typing___Optional[MetaDataV1.Environment] = None,
        sending_service : typing___Optional[typing___Text] = None,
        offset : typing___Optional[builtin___int] = None,
        partition : typing___Optional[builtin___int] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> MetaDataV1: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"environment",u"iso_date",u"offset",u"partition",u"sending_service"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"environment",b"environment",u"iso_date",b"iso_date",u"offset",b"offset",u"partition",b"partition",u"sending_service",b"sending_service"]) -> None: ...
