# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ftfbroker/protobuf/ftf/rocketchat_mensa.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ftfbroker.protobuf.common import metaData_pb2 as ftfbroker_dot_protobuf_dot_common_dot_metaData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ftfbroker/protobuf/ftf/rocketchat_mensa.proto',
  package='ftfbroker.protobuf.ftf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n-ftfbroker/protobuf/ftf/rocketchat_mensa.proto\x12\x16\x66tfbroker.protobuf.ftf\x1a(ftfbroker/protobuf/common/metaData.proto\"\x9f\x01\n\x0fRocketchatMensa\x12\x38\n\x07meta_v1\x18\x01 \x01(\x0b\x32%.ftfbroker.protobuf.common.MetaDataV1H\x00\x12?\n\npayload_v1\x18\x02 \x01(\x0b\x32).ftfbroker.protobuf.ftf.RocketchatMensaV1H\x01\x42\x06\n\x04metaB\t\n\x07payload\"\x13\n\x11RocketchatMensaV1b\x06proto3')
  ,
  dependencies=[ftfbroker_dot_protobuf_dot_common_dot_metaData__pb2.DESCRIPTOR,])




_ROCKETCHATMENSA = _descriptor.Descriptor(
  name='RocketchatMensa',
  full_name='ftfbroker.protobuf.ftf.RocketchatMensa',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='meta_v1', full_name='ftfbroker.protobuf.ftf.RocketchatMensa.meta_v1', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload_v1', full_name='ftfbroker.protobuf.ftf.RocketchatMensa.payload_v1', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='meta', full_name='ftfbroker.protobuf.ftf.RocketchatMensa.meta',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='payload', full_name='ftfbroker.protobuf.ftf.RocketchatMensa.payload',
      index=1, containing_type=None, fields=[]),
  ],
  serialized_start=116,
  serialized_end=275,
)


_ROCKETCHATMENSAV1 = _descriptor.Descriptor(
  name='RocketchatMensaV1',
  full_name='ftfbroker.protobuf.ftf.RocketchatMensaV1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=296,
)

_ROCKETCHATMENSA.fields_by_name['meta_v1'].message_type = ftfbroker_dot_protobuf_dot_common_dot_metaData__pb2._METADATAV1
_ROCKETCHATMENSA.fields_by_name['payload_v1'].message_type = _ROCKETCHATMENSAV1
_ROCKETCHATMENSA.oneofs_by_name['meta'].fields.append(
  _ROCKETCHATMENSA.fields_by_name['meta_v1'])
_ROCKETCHATMENSA.fields_by_name['meta_v1'].containing_oneof = _ROCKETCHATMENSA.oneofs_by_name['meta']
_ROCKETCHATMENSA.oneofs_by_name['payload'].fields.append(
  _ROCKETCHATMENSA.fields_by_name['payload_v1'])
_ROCKETCHATMENSA.fields_by_name['payload_v1'].containing_oneof = _ROCKETCHATMENSA.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['RocketchatMensa'] = _ROCKETCHATMENSA
DESCRIPTOR.message_types_by_name['RocketchatMensaV1'] = _ROCKETCHATMENSAV1
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RocketchatMensa = _reflection.GeneratedProtocolMessageType('RocketchatMensa', (_message.Message,), {
  'DESCRIPTOR' : _ROCKETCHATMENSA,
  '__module__' : 'ftfbroker.protobuf.ftf.rocketchat_mensa_pb2'
  # @@protoc_insertion_point(class_scope:ftfbroker.protobuf.ftf.RocketchatMensa)
  })
_sym_db.RegisterMessage(RocketchatMensa)

RocketchatMensaV1 = _reflection.GeneratedProtocolMessageType('RocketchatMensaV1', (_message.Message,), {
  'DESCRIPTOR' : _ROCKETCHATMENSAV1,
  '__module__' : 'ftfbroker.protobuf.ftf.rocketchat_mensa_pb2'
  # @@protoc_insertion_point(class_scope:ftfbroker.protobuf.ftf.RocketchatMensaV1)
  })
_sym_db.RegisterMessage(RocketchatMensaV1)


# @@protoc_insertion_point(module_scope)
